=== ArchitectVVN/FileS/project_root/output/file_info_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "FileInfo List",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "filename": {
                "type": "string"
            },
            "full_path": {
                "type": "string"
            },
            "file_size": {
                "type": "integer",
                "minimum": 0
            },
            "creation_date": {
                "type": "string"
            },
            "last_modified": {
                "type": "string"
            }
        },
        "required": [
            "filename",
            "full_path",
            "file_size",
            "creation_date",
            "last_modified"
        ]
    }
}

=== ArchitectVVN/FileS/project_root/output/file_info.json
[
    {
        "filename": "example_ascii_processed.txt",
        "full_path": "project_root\\data\\processed\\example_ascii_processed.txt",
        "file_size": 26,
        "creation_date": "2024-12-28 10:03:10",
        "last_modified": "2024-12-28 10:03:10"
    },
    {
        "filename": "example_iso_processed.txt",
        "full_path": "project_root\\data\\processed\\example_iso_processed.txt",
        "file_size": 38,
        "creation_date": "2024-12-28 10:03:10",
        "last_modified": "2024-12-28 10:03:10"
    },
    {
        "filename": "example_utf8_processed.txt",
        "full_path": "project_root\\data\\processed\\example_utf8_processed.txt",
        "file_size": 41,
        "creation_date": "2024-12-28 10:03:10",
        "last_modified": "2024-12-28 10:03:10"
    }
]
